[package]
name = "aestub"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["tokio"] }
clap = { version = "4.5.47", features = ["derive"] }
nom = "8.0.0"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
